// Number Guessing Game
// This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.
"#! /Usr/bin/env.node";
import inquirer from "inquirer";
import chalk from "chalk";

const min = 1;
const max = 100;
let totalAttempts = 0;
let userGuess;
const difficulties = [
    "Easy - 10 Attempts",
    "Medium - 6 Attempts",
    "Hard - 4 Attempts",
];
const randomNumber = Math.floor(Math.random() * (max - min));
console.log(chalk.blue.bold("---------------------------------"));
console.log(chalk.blueBright.bold("\tNumber Guessing Game"));
console.log(chalk.blue.bold("---------------------------------\n\n"));
const { difficulty } = await inquirer.prompt({
    message: "Select Difficulty: ",
    type: "rawlist",
    name: "difficulty",
    choices: difficulties,
});
if (difficulty === difficulties[0]) {
    totalAttempts = 10;
}
else if (difficulty === difficulties[1]) {
    totalAttempts = 6;
}
else if (difficulty === difficulties[2]) {
    totalAttempts = 4;
}
console.log("-------------------------------------------------------------");
console.log(chalk.whiteBright(`\nYou have to Guess a Number Between 1 - 100 in ${totalAttempts} attempts\n`));
console.log("-------------------------------------------------------------");
while (totalAttempts > 0) {
    const { guess } = await inquirer.prompt({
        message: "Enter your Guess: ",
        type: "number",
        name: "guess",
    });
    userGuess = Number(guess);
    if (userGuess > 100 || userGuess <= 0) {
        console.log(chalk.black.bgBlueBright.bold("The number is Out of Range.\nPlease Enter a Number between 1 - 100"));
    }
    if (userGuess === randomNumber) {
        console.log(chalk.green.bold("\n--------------------------------------"));
        console.log(chalk.greenBright.bold("\tCongratulations! You Win"));
        console.log(chalk.greenBright.bold(`\tSecret Number: ${randomNumber}`));
        console.log(chalk.green.bold("--------------------------------------"));
        break;
    }
    else if (userGuess < randomNumber) {
        console.log("The number is Higher. Try Again!\n");
    }
    else if (userGuess > randomNumber) {
        console.log("The number is Lower. Try Again!\n");
    }
    else {
        console.log("Invalid Input. Please Enter a Number.\n");
    }
    totalAttempts -= 1;
    console.log(chalk.yellowBright.underline.bold(`Attempts Left: ${totalAttempts}`));
    if (totalAttempts == 0) {
        console.log(chalk.redBright.bold("You Loose. "));
        console.log(chalk.green.underline.bold(`Secret Number: ${randomNumber}`));
    }
}
